//
//  ListingService.swift
//  roomieverse-ios
//
//  High-level service for room listing operations
//

import Foundation
import Combine

class ListingService: ObservableObject {
    static let shared = ListingService()
    
    @Published var listings: [RoomListing] = []
    @Published var isLoading = false
    @Published var errorMessage: String?
    
    private let firestore = FirestoreService.shared
    private var cancellables = Set<AnyCancellable>()
    
    private init() {}
    
    // MARK: - Fetch Listings
    
    func fetchListings(category: ListingCategory? = nil) async {
        isLoading = true
        errorMessage = nil
        
        do {
            let apiListings = try await firestore.fetchListings(
                category: category?.rawValue,
                status: .active
            )
            
            // Convert API models to app models
            await MainActor.run {
                self.listings = apiListings.compactMap { convertToAppModel($0) }
                self.isLoading = false
            }
        } catch {
            await MainActor.run {
                self.errorMessage = error.localizedDescription
                self.isLoading = false
                
                // Fallback to mock data if Firebase not configured
                if self.listings.isEmpty {
                    self.listings = MockData.listings
                    if let category = category {
                        self.listings = self.listings.filter { $0.category == category }
                    }
                }
            }
        }
    }
    
    func fetchListing(id: String) async -> RoomListing? {
        do {
            let apiListing = try await firestore.fetchListing(id: id)
            return convertToAppModel(apiListing)
        } catch {
            // Fallback to mock data
            return MockData.listings.first { $0.id == id }
        }
    }
    
    // MARK: - Create/Update/Delete
    
    func createListing(
        title: String,
        category: ListingCategory,
        roommateType: RoommateType?,
        price: Int,
        location: String,
        district: String,
        city: String,
        moveInDate: String,
        description: String,
        introduction: String,
        phone: String,
        amenities: [String],
        images: [String]
    ) async throws -> String {
        
        guard let userId = FirebaseManager.shared.currentUser?.uid else {
            throw NSError(domain: "Auth", code: -1, userInfo: [
                NSLocalizedDescriptionKey: "User not authenticated"
            ])
        }
        
        let apiListing = APIRoomListing(
            id: "", // Will be generated by Firestore
            title: title,
            author: FirebaseManager.shared.currentUser?.displayName ?? "Anonymous",
            price: "\(price)",
            location: location,
            city: city,
            district: district,
            specificAddress: nil,
            buildingName: nil,
            moveInDate: moveInDate,
            timeNegotiable: false,
            description: description,
            introduction: introduction,
            category: category.rawValue,
            roommateType: roommateType?.rawValue,
            propertyTypes: nil,
            phone: phone,
            zalo: nil,
            facebook: nil,
            instagram: nil,
            images: images,
            amenities: amenities,
            userId: userId,
            status: APIConfig.moderationEnabled ? .pending : .active,
            costs: nil,
            preferences: nil,
            roomSize: nil,
            currentOccupants: nil,
            totalRooms: nil,
            minContractDuration: nil,
            viewCount: 0,
            favoriteCount: 0,
            moderatedBy: nil,
            moderatedAt: nil,
            moderationNote: nil,
            rejectionReason: nil,
            createdAt: ISO8601DateFormatter().string(from: Date()),
            updatedAt: ISO8601DateFormatter().string(from: Date())
        )
        
        return try await firestore.createListing(apiListing)
    }
    
    func updateListing(id: String, updates: [String: Any]) async throws {
        // Fetch existing, apply updates, save back
        var listing = try await firestore.fetchListing(id: id)
        
        // Apply updates (would need proper model mutation)
        // This is simplified - in real app you'd have a builder pattern
        
        try await firestore.updateListing(listing)
    }
    
    func deleteListing(id: String) async throws {
        try await firestore.deleteListing(id: id)
    }
    
    // MARK: - View Count
    
    func incrementViewCount(listingId: String) {
        Task {
            try? await firestore.incrementViewCount(listingId: listingId)
        }
    }
    
    // MARK: - Favorites
    
    func fetchUserFavorites(userId: String) async -> [RoomListing] {
        do {
            let favorites = try await firestore.fetchUserFavorites(userId: userId)
            let listingIds = favorites.map { $0.listingId }
            
            // Fetch all favorited listings
            var favoritedListings: [RoomListing] = []
            for id in listingIds {
                if let listing = await fetchListing(id: id) {
                    favoritedListings.append(listing)
                }
            }
            return favoritedListings
        } catch {
            return []
        }
    }
    
    func addFavorite(userId: String, listingId: String) async throws {
        try await firestore.addFavorite(userId: userId, listingId: listingId)
    }
    
    func removeFavorite(userId: String, listingId: String) async throws {
        try await firestore.removeFavorite(userId: userId, listingId: listingId)
    }
    
    // MARK: - Reports
    
    func reportListing(listingId: String, reportedBy: String, reason: String, details: String?) async throws {
        try await firestore.createReport(
            listingId: listingId,
            reportedBy: reportedBy,
            reason: reason,
            details: details
        )
    }
    
    // MARK: - Image Upload
    
    func uploadListingImages(_ images: [Data], listingId: String) async throws -> [String] {
        var urls: [String] = []
        
        for (index, imageData) in images.enumerated() {
            let publicUrl = try await ImageUploadService.shared.uploadImage(
                imageData,
                folder: "listings",
                id: listingId,
                filename: "image-\(index).jpg"
            )
            urls.append(publicUrl)
        }
        
        return urls
    }
    
    // MARK: - Model Conversion
    
    func convertToAppModel(_ apiListing: APIRoomListing) -> RoomListing? {
        guard let category = ListingCategory(rawValue: apiListing.category) else {
            return nil
        }
        
        var roommateType: RoommateType?
        if let rtString = apiListing.roommateType {
            roommateType = RoommateType(rawValue: rtString)
        }
        
        // Parse price string to Int
        let priceInt = Int(apiListing.price.replacingOccurrences(of: "[^0-9]", with: "", options: .regularExpression)) ?? 0
        
        let dateFormatter = ISO8601DateFormatter()
        let createdAt = apiListing.createdAt.flatMap { dateFormatter.date(from: $0) } ?? Date()
        
        return RoomListing(
            id: apiListing.id,
            title: apiListing.title,
            authorId: apiListing.userId,
            authorName: apiListing.author,
            authorAvatar: "person.circle.fill",
            category: category,
            roommateType: roommateType,
            price: priceInt,
            location: apiListing.location,
            district: apiListing.district ?? "",
            city: apiListing.city ?? "Ho Chi Minh",
            moveInDate: apiListing.moveInDate,
            description: apiListing.description,
            introduction: apiListing.introduction,
            images: apiListing.images,
            amenities: apiListing.amenities ?? [],
            phone: apiListing.phone,
            zalo: apiListing.zalo,
            facebook: apiListing.facebook,
            roomSize: apiListing.roomSize,
            currentOccupants: apiListing.currentOccupants,
            status: apiListing.status ?? .active,
            viewCount: apiListing.viewCount ?? 0,
            favoriteCount: apiListing.favoriteCount ?? 0,
            createdAt: createdAt,
            isFeatured: false,
            preferredGender: apiListing.preferences?.gender?.first,
            preferredStatus: apiListing.preferences?.status?.first,
            schedule: apiListing.preferences?.schedule?.first,
            cleanliness: apiListing.preferences?.cleanliness?.first,
            habits: apiListing.preferences?.habits ?? [],
            pets: apiListing.preferences?.pets?.first
        )
    }
}

// MARK: - Community Service

class CommunityService: ObservableObject {
    static let shared = CommunityService()
    
    @Published var posts: [CommunityPost] = []
    @Published var isLoading = false
    @Published var errorMessage: String?
    
    private let firestore = FirestoreService.shared
    
    private init() {}
    
    func fetchPosts(category: CommunityCategory? = nil, hot: Bool? = nil) async {
        isLoading = true
        errorMessage = nil
        
        do {
            let apiPosts = try await firestore.fetchCommunityPosts(
                category: category?.rawValue,
                hot: hot
            )
            
            await MainActor.run {
                self.posts = apiPosts.compactMap { convertToAppModel($0) }
                self.isLoading = false
            }
        } catch {
            await MainActor.run {
                self.errorMessage = error.localizedDescription
                self.isLoading = false
                
                // Fallback to mock data
                if self.posts.isEmpty {
                    self.posts = MockData.communityPosts
                    if let category = category {
                        self.posts = self.posts.filter { $0.category == category }
                    }
                    if let hot = hot {
                        self.posts = self.posts.filter { $0.isHot == hot }
                    }
                }
            }
        }
    }
    
    func fetchPost(id: String) async -> CommunityPost? {
        do {
            let apiPost = try await firestore.fetchCommunityPost(id: id)
            return convertToAppModel(apiPost)
        } catch {
            return MockData.communityPosts.first { $0.id == id }
        }
    }
    
    func incrementViews(postId: String) {
        Task {
            try? await firestore.incrementPostViews(postId: postId)
        }
    }
    
    func convertToAppModel(_ apiPost: APICommunityPost) -> CommunityPost? {
        guard let category = CommunityCategory(rawValue: apiPost.category) else {
            return nil
        }
        
        let dateFormatter = ISO8601DateFormatter()
        let createdAt = apiPost.createdAt.flatMap { dateFormatter.date(from: $0) } ?? Date()
        
        return CommunityPost(
            id: apiPost.id ?? UUID().uuidString,
            authorId: apiPost.authorId,
            authorName: apiPost.authorName,
            authorAvatar: apiPost.authorPhoto ?? "person.circle.fill",
            category: category,
            title: apiPost.title,
            preview: apiPost.preview,
            content: apiPost.content,
            likes: apiPost.likes,
            comments: apiPost.comments,
            views: apiPost.views,
            isHot: apiPost.hot ?? false,
            createdAt: createdAt
        )
    }
}
