//
//  MockData.swift
//  roomieverse-ios
//

import Foundation

struct MockData {

    // MARK: - Listings

    static let listings: [RoomListing] = [
        RoomListing(
            id: "1",
            title: "Tìm người ở ghép tại Vinhomes Central Park",
            authorId: "user-mock-1",
            authorName: "Minh Anh",
            authorAvatar: "person.circle.fill",
            category: .roommate,
            roommateType: .haveRoom,
            price: 4500000,
            location: "Vinhomes Central Park, Bình Thạnh",
            district: "Bình Thạnh",
            city: "TP. Hồ Chí Minh",
            moveInDate: "01/03/2026",
            description: "Phòng rộng rãi, thoáng mát, view sông Sài Gòn cực đẹp. Có ban công, tủ quần áo, giường ngủ. Full nội thất cao cấp. Chỉ cần mang theo quần áo là vào ở được ngay.",
            introduction: "Mình là dân văn phòng, làm tại Q1, sạch sẽ, ngăn nắp, không hút thuốc. Tìm bạn có lối sống tương tự để ở ghép.",
            images: [],
            amenities: ["ac", "wifi", "washing", "fridge", "parking", "elevator"],
            phone: "0901234567",
            zalo: "0901234567",
            facebook: nil,
            roomSize: "20",
            currentOccupants: "1",
            status: .active,
            viewCount: 124,
            favoriteCount: 18,
            createdAt: Date().addingTimeInterval(-86400 * 2),
            isFeatured: true,
            preferredGender: "female",
            preferredStatus: "worker",
            schedule: "early",
            cleanliness: "very-clean",
            habits: ["no-smoke"],
            pets: "no-pets"
        ),
        RoomListing(
            id: "2",
            title: "Phòng trọ mới xây, có nội thất tại Thủ Đức",
            authorId: "user-mock-2",
            authorName: "Quang Huy",
            authorAvatar: "person.circle.fill",
            category: .roomshare,
            roommateType: nil,
            price: 3200000,
            location: "Đường Tô Ngọc Vân, TP. Thủ Đức",
            district: "TP. Thủ Đức",
            city: "TP. Hồ Chí Minh",
            moveInDate: "15/02/2026",
            description: "Phòng trọ mới xây 2023, diện tích 20m², trang bị đầy đủ nội thất cơ bản: máy lạnh, giường, tủ quần áo, kệ bếp. Gần ĐHQG TP.HCM, siêu thị, quán ăn.",
            introduction: "Nhà trọ yên tĩnh, an ninh tốt. Chủ nhà thân thiện, dễ tính.",
            images: [],
            amenities: ["ac", "wifi", "fridge"],
            phone: "0912345678",
            zalo: "0912345678",
            facebook: nil,
            roomSize: "20",
            currentOccupants: nil,
            status: .active,
            viewCount: 89,
            favoriteCount: 12,
            createdAt: Date().addingTimeInterval(-86400 * 3),
            isFeatured: true,
            preferredGender: nil,
            preferredStatus: nil,
            schedule: nil,
            cleanliness: nil,
            habits: [],
            pets: nil
        ),
        RoomListing(
            id: "3",
            title: "Cần tìm bạn ở ghép căn hộ Masteri Quận 9",
            authorId: "user-mock-3",
            authorName: "Thu Hương",
            authorAvatar: "person.circle.fill",
            category: .roommate,
            roommateType: .haveRoom,
            price: 5000000,
            location: "Masteri Waterfront, Quận 9",
            district: "Quận 9",
            city: "TP. Hồ Chí Minh",
            moveInDate: "01/03/2026",
            description: "Căn hộ 2PN tại Masteri Waterfront. Phòng cho thuê rộng 15m², có ban công, nhìn ra hồ bơi. Nội thất đầy đủ cao cấp.",
            introduction: "Mình là giáo viên, 27 tuổi. Sống ngăn nắp, thích yên tĩnh. Mong tìm được bạn cùng chí hướng.",
            images: [],
            amenities: ["ac", "wifi", "washing", "fridge", "elevator"],
            phone: "0923456789",
            zalo: nil,
            facebook: "Thu.Huong.123",
            roomSize: "15",
            currentOccupants: "1",
            status: .active,
            viewCount: 203,
            favoriteCount: 31,
            createdAt: Date().addingTimeInterval(-86400),
            isFeatured: false,
            preferredGender: "female",
            preferredStatus: nil,
            schedule: "flexible",
            cleanliness: "very-clean",
            habits: ["no-smoke", "no-alcohol"],
            pets: "no-pets"
        ),
        RoomListing(
            id: "4",
            title: "Tìm phòng ghép khu vực Quận 3, ngân sách 3-4 triệu",
            authorId: "user-mock-4",
            authorName: "Đức Thịnh",
            authorAvatar: "person.circle.fill",
            category: .roommate,
            roommateType: .findPartner,
            price: 3500000,
            location: "Quận 3, TP. Hồ Chí Minh",
            district: "Quận 3",
            city: "TP. Hồ Chí Minh",
            moveInDate: "Thỏa thuận",
            description: "Mình đang tìm phòng ghép hoặc căn hộ mini tại khu vực Q3 hoặc các quận lân cận (Q1, Q10, Bình Thạnh). Ngân sách 3-4 triệu/tháng bao gồm điện nước.",
            introduction: "Mình 25 tuổi, làm IT tại Q3. Sạch sẽ, ngăn nắp. Thường về nhà muộn nhưng không gây ồn ào.",
            images: [],
            amenities: [],
            phone: "0934567890",
            zalo: "0934567890",
            facebook: nil,
            roomSize: nil,
            currentOccupants: nil,
            status: .active,
            viewCount: 67,
            favoriteCount: 5,
            createdAt: Date().addingTimeInterval(-86400 * 5),
            isFeatured: false,
            preferredGender: nil,
            preferredStatus: nil,
            schedule: "late",
            cleanliness: "normal",
            habits: ["no-smoke"],
            pets: nil
        ),
        RoomListing(
            id: "5",
            title: "Căn hộ ngắn hạn tại Sky Villa Đà Lạt",
            authorId: "user-mock-5",
            authorName: "Ngọc Linh",
            authorAvatar: "person.circle.fill",
            category: .shortTerm,
            roommateType: nil,
            price: 800000,
            location: "Đường Nguyễn Trãi, Đà Lạt",
            district: "Đà Lạt",
            city: "Lâm Đồng",
            moveInDate: "Linh hoạt",
            description: "Studio view đồi thông cực đẹp. Phù hợp cho digital nomad, remote worker muốn trải nghiệm làm việc tại Đà Lạt. Giá tháng rất tốt so với thuê theo ngày.",
            introduction: "Không gian yên tĩnh, cà phê sẵn có, wifi tốc độ cao. Bãi đỗ xe miễn phí.",
            images: [],
            amenities: ["ac", "wifi", "washing", "fridge", "parking"],
            phone: "0945678901",
            zalo: "0945678901",
            facebook: nil,
            roomSize: "30",
            currentOccupants: nil,
            status: .active,
            viewCount: 312,
            favoriteCount: 47,
            createdAt: Date().addingTimeInterval(-86400 * 7),
            isFeatured: true,
            preferredGender: nil,
            preferredStatus: nil,
            schedule: nil,
            cleanliness: nil,
            habits: [],
            pets: nil
        ),
        RoomListing(
            id: "6",
            title: "Sang nhượng hợp đồng thuê căn hộ 2PN tại Q7",
            authorId: "user-mock-6",
            authorName: "Bảo Trân",
            authorAvatar: "person.circle.fill",
            category: .sublease,
            roommateType: nil,
            price: 12000000,
            location: "Sunrise City, Quận 7",
            district: "Quận 7",
            city: "TP. Hồ Chí Minh",
            moveInDate: "01/04/2026",
            description: "Cần sang nhượng hợp đồng thuê căn hộ 2PN tại Sunrise City. Còn 8 tháng hợp đồng. Giá thuê hiện tại 12 triệu/tháng, thấp hơn thị trường. Nội thất đầy đủ cao cấp.",
            introduction: "Lý do: Gia đình có việc, cần về quê sinh sống. Người nhận hợp đồng chỉ cần đặt cọc 1 tháng.",
            images: [],
            amenities: ["ac", "wifi", "washing", "fridge", "parking", "elevator"],
            phone: "0956789012",
            zalo: "0956789012",
            facebook: nil,
            roomSize: "70",
            currentOccupants: "2",
            status: .active,
            viewCount: 445,
            favoriteCount: 63,
            createdAt: Date().addingTimeInterval(-86400 * 10),
            isFeatured: true,
            preferredGender: nil,
            preferredStatus: nil,
            schedule: nil,
            cleanliness: nil,
            habits: [],
            pets: nil
        ),
        RoomListing(
            id: "7",
            title: "Phòng trọ giá rẻ khu sinh viên gần RMIT",
            authorId: "user-mock-7",
            authorName: "Văn Khoa",
            authorAvatar: "person.circle.fill",
            category: .roomshare,
            roommateType: nil,
            price: 2200000,
            location: "Đường Nguyễn Văn Tráng, Quận 1",
            district: "Quận 1",
            city: "TP. Hồ Chí Minh",
            moveInDate: "Ngay lập tức",
            description: "Phòng trọ 16m², có máy lạnh, wifi. Vị trí đắc địa ngay Q1, gần RMIT, Bến Thành, nhiều quán ăn và café xung quanh.",
            introduction: "Nhà yên tĩnh, cấm hút thuốc. Phù hợp sinh viên hoặc người mới đi làm.",
            images: [],
            amenities: ["ac", "wifi"],
            phone: "0967890123",
            zalo: "0967890123",
            facebook: nil,
            roomSize: "16",
            currentOccupants: nil,
            status: .active,
            viewCount: 178,
            favoriteCount: 24,
            createdAt: Date().addingTimeInterval(-86400 * 4),
            isFeatured: false,
            preferredGender: nil,
            preferredStatus: "student",
            schedule: nil,
            cleanliness: nil,
            habits: ["no-smoke"],
            pets: nil
        ),
        RoomListing(
            id: "8",
            title: "Tìm bạn nữ ở ghép tại Lavida+ Quận 7",
            authorId: "user-mock-8",
            authorName: "Phương Thảo",
            authorAvatar: "person.circle.fill",
            category: .roommate,
            roommateType: .haveRoom,
            price: 4000000,
            location: "Lavida+, Quận 7",
            district: "Quận 7",
            city: "TP. Hồ Chí Minh",
            moveInDate: "01/03/2026",
            description: "Phòng ngủ riêng trong căn hộ 2PN tại Lavida+. Chia sẻ phòng khách, nhà bếp, 2 vệ sinh. Giá đã bao điện nước internet.",
            introduction: "Mình 26 tuổi, làm marketing. Thích nấu ăn, xem phim. Tìm bạn nữ vui vẻ, không hút thuốc.",
            images: [],
            amenities: ["ac", "wifi", "washing", "fridge", "elevator"],
            phone: "0978901234",
            zalo: "0978901234",
            facebook: "Phuong.Thao.HCM",
            roomSize: "18",
            currentOccupants: "1",
            status: .active,
            viewCount: 267,
            favoriteCount: 38,
            createdAt: Date().addingTimeInterval(-86400 * 1),
            isFeatured: true,
            preferredGender: "female",
            preferredStatus: "worker",
            schedule: "flexible",
            cleanliness: "normal",
            habits: ["no-smoke"],
            pets: "cats-ok"
        )
    ]

    // MARK: - Community Posts

    static let communityPosts: [CommunityPost] = [
        CommunityPost(
            id: "c1",
            authorId: "admin-1",
            authorName: "Roomie Team",
            authorAvatar: "person.circle.fill",
            category: .tips,
            title: "5 điều cần hỏi trước khi ký hợp đồng thuê nhà",
            preview: "Nhiều bạn hay bỏ qua những điều này và hối hận sau đó. Mình tổng hợp 5 câu hỏi quan trọng nhất bạn cần hỏi chủ nhà trước khi ký hợp đồng...",
            content: "Nhiều bạn hay bỏ qua những điều này và hối hận sau đó.\n\n**1. Giá điện nước tính như thế nào?**\nHỏi rõ giá điện/nước, đừng để chủ nhà nói 'tính theo giá nhà nước' rồi sau lại tính cao hơn.\n\n**2. Hợp đồng bao nhiêu tháng? Thông báo trước mấy tháng?**\nRất quan trọng! Nhiều chủ nhà đòi thông báo 2-3 tháng trước khi dọn.\n\n**3. Có được sửa chữa/thay đổi nội thất không?**\nNếu muốn treo tranh, đóng kệ, bạn cần hỏi rõ.\n\n**4. Phí quản lý toà nhà (nếu chung cư) ai trả?**\nMột số chủ nhà đẩy phí này sang người thuê.\n\n**5. Có camera an ninh trong nhà không?**\nQuyền riêng tư của bạn cần được đảm bảo.",
            images: [],
            likes: 234,
            comments: 45,
            views: 1203,
            isHot: true,
            createdAt: Date().addingTimeInterval(-86400 * 1)
        ),
        CommunityPost(
            id: "c2",
            authorId: "user-c2",
            authorName: "Lan Anh",
            authorAvatar: "person.circle.fill",
            category: .drama,
            title: "Ở ghép 6 tháng mới phát hiện bạn cùng phòng không bao giờ rửa bát",
            preview: "Câu chuyện bi hài về việc ở ghép với người bạn tưởng tốt mà hóa ra là... thảm họa sinh hoạt.",
            content: "Câu chuyện này xảy ra với mình vào năm ngoái...\n\nMình và T. là bạn học từ đại học, quen biết nhau cũng khá lâu. Khi cả hai cùng lên Sài Gòn làm việc, tự nhiên T. đề xuất ở ghép để tiết kiệm chi phí và mình đồng ý ngay.\n\n6 tháng đầu mọi thứ đều ổn... cho đến khi mình để ý thấy mình luôn là người rửa bát cuối cùng mỗi tối. Ban đầu mình nghĩ T. bận, nhưng sau 2 tuần không thấy T. rửa bát một lần nào...\n\nHóa ra T. có quan điểm: 'Ai nấu thì không rửa, ai không nấu thì rửa'. Mà T. không bao giờ nấu, nhưng cũng không bao giờ rửa vì 'hôm nay mình mệt'.",
            images: [],
            likes: 512,
            comments: 89,
            views: 3401,
            isHot: true,
            createdAt: Date().addingTimeInterval(-86400 * 3)
        ),
        CommunityPost(
            id: "c3",
            authorId: "user-c3",
            authorName: "Minh Tuấn",
            authorAvatar: "person.circle.fill",
            category: .review,
            title: "Review chung cư The Sun Avenue - Ở 1 năm, đây là cảm nhận thật",
            preview: "Sau 1 năm ở tại The Sun Avenue, mình muốn chia sẻ review thật sự, không qua trung gian hay môi giới.",
            content: "**Ưu điểm:**\n\n✅ Vị trí đắc địa - cạnh sông, gần Metro\n✅ Tiện ích đầy đủ: hồ bơi, gym, sân chơi trẻ em\n✅ An ninh 24/7, có camera\n✅ Hầm xe rộng rãi\n✅ View đẹp từ tầng 20 trở lên\n\n**Nhược điểm:**\n\n❌ Thang máy hay hỏng vào giờ cao điểm\n❌ Phí quản lý cao (25k/m²)\n❌ Siêu thị trong tòa đắt hơn bên ngoài\n❌ Tiếng ồn từ tầng trên khá nhiều\n\n**Kết luận:** 7/10 - Sống được, nhưng đắt.",
            images: [],
            likes: 156,
            comments: 32,
            views: 892,
            isHot: false,
            createdAt: Date().addingTimeInterval(-86400 * 5)
        ),
        CommunityPost(
            id: "c4",
            authorId: "user-c4",
            authorName: "Hà Linh",
            authorAvatar: "person.circle.fill",
            category: .passDo,
            title: "Pass bộ sofa da PU 3 chỗ ngồi - giá 1.2 triệu",
            preview: "Dọn nhà cần pass nhanh. Sofa da PU màu xám, 3 chỗ ngồi, mua từ IKEA giá 4.5 triệu, dùng được 1.5 năm, còn tốt.",
            content: "Dọn nhà cần pass nhanh.\n\n**Thông tin sản phẩm:**\n- Sofa da PU màu xám nhạt\n- 3 chỗ ngồi, kích thước: 200x85x85cm\n- Mua từ IKEA giá 4.5 triệu, dùng được 1.5 năm\n- Còn tốt, không rách, không phai màu\n- Có thể test tại nhà\n\n**Giá pass:** 1.2 triệu (không thương lượng)\n**Địa điểm:** Quận 7, TP.HCM\n**Giao nhận:** Người mua tự đến lấy hoặc thuê shipper\n\nLiên hệ zalo: 0909xxxxxx",
            images: [],
            likes: 23,
            comments: 14,
            views: 234,
            isHot: false,
            createdAt: Date().addingTimeInterval(-86400 * 2)
        ),
        CommunityPost(
            id: "c5",
            authorId: "user-c5",
            authorName: "Quốc Bảo",
            authorAvatar: "person.circle.fill",
            category: .blog,
            title: "Hành trình tìm nhà trọ ở Sài Gòn: Từ thất bại đến thành công",
            preview: "6 tháng, 23 lần đi xem phòng, 4 lần bị 'ăn quả đắng'. Đây là bài học mình rút ra được sau hành trình tìm nhà tại Sài Gòn.",
            content: "Khi mới lên Sài Gòn năm 2023, mình không có khái niệm gì về thị trường nhà trọ ở đây...\n\n**Lần 1 - Bài học về đặt cọc qua mạng:**\nMình thấy một bài đăng phòng đẹp, giá tốt trên Facebook. Vì ở tỉnh lên chưa có thời gian đi xem, mình đã đặt cọc 1 triệu qua chuyển khoản. Kết quả: số điện thoại bị chặn.\n\n**Lần 2 - Bài học về đọc kỹ hợp đồng:**\n...\n\n**Bài học cuối cùng:**\nHãy dùng các nền tảng uy tín như RoomieVerse để tìm phòng. Thông tin được kiểm duyệt, bạn kết nối trực tiếp với người cho thuê, không qua môi giới.",
            images: [],
            likes: 389,
            comments: 67,
            views: 2156,
            isHot: true,
            createdAt: Date().addingTimeInterval(-86400 * 7)
        )
    ]
}
